.TH CLIENT 1 "September 2025" "Version 0.4.1" "User Commands"
.SH NAME
client \- A demo client program using custom string and file utility functions
.SH SYNOPSIS
.B client
[file]
.SH DESCRIPTION
The
.B client
program demonstrates the use of custom string and file handling functions.  
It supports testing string functions (like mystrlen, mystrcpy) and file functions  
(wordCount, mygrep).  
.SH AUTHOR
Faheem Ahmad <bsdsf23m025@gmail.com>


